#!/usr/bin/env python3
"""
Quick Test - LangManus Core Functionality

Tests core framework functionality without requiring external API dependencies.
"""

import sys
import os
sys.path.append('src')

def test_core_imports():
    """Test core module imports."""
    print("🔍 Testing core imports...")
    
    try:
        # Test direct tool imports (avoiding __init__.py that imports external deps)
        from tools.python_tools import execute_python_code, execute_repl_code
        print("✅ Python tools imported successfully")
        
        from tools.file_tools import save_report, write_file
        print("✅ File tools imported successfully")
        
        from tools.bash_tool import execute_bash_command
        print("✅ Bash tools imported successfully")
        
        from tools.decorators import safe_execute, retry
        print("✅ Decorators imported successfully")
        
        from config.tools import OUTPUT_DIR, CHART_OUTPUT_DIR
        print("✅ Config imported successfully")
        
        return True
        
    except Exception as e:
        print(f"❌ Import error: {e}")
        return False


def test_python_tools():
    """Test Python execution tools."""
    print("\n🐍 Testing Python tools...")
    
    try:
        from tools.python_tools import execute_python_code
        
        # Test simple code execution
        result = execute_python_code("print('Hello LangManus!')")
        if result['success']:
            print("✅ Python code execution working")
            print(f"   Output: {result['stdout'].strip()}")
        else:
            print(f"❌ Python execution failed: {result['error']}")
            
        # Test math calculation
        result = execute_python_code("result = 2 + 2\nprint(f'2 + 2 = {result}')")
        if result['success']:
            print("✅ Python math calculation working")
            print(f"   Output: {result['stdout'].strip()}")
            
        return True
        
    except Exception as e:
        print(f"❌ Python tools error: {e}")
        return False


def test_file_tools():
    """Test file management tools."""
    print("\n📁 Testing file tools...")
    
    try:
        from tools.file_tools import save_report, write_file
        
        # Test report saving
        report_content = """# Test Report

This is a test report generated by LangManus.

## Results
- ✅ File tools are working
- ✅ Report generation successful
"""
        
        result = save_report(report_content, "test_report.md", "test_output")
        if result['success']:
            print("✅ Report saving working")
            print(f"   Saved to: {result['file_path']}")
        else:
            print(f"❌ Report saving failed: {result['error']}")
            
        # Test JSON file writing
        test_data = {"framework": "LangManus", "status": "working", "tools": ["python", "file", "bash"]}
        result = write_file("test_output/test_data.json", test_data)
        if result['success']:
            print("✅ JSON file writing working")
            print(f"   File: {result['file_path']}")
            
        return True
        
    except Exception as e:
        print(f"❌ File tools error: {e}")
        return False


def test_bash_tools():
    """Test bash execution tools."""
    print("\n💻 Testing bash tools...")
    
    try:
        from tools.bash_tool import execute_bash_command
        
        # Test simple command
        result = execute_bash_command("echo 'LangManus bash tools working!'")
        if result['success']:
            print("✅ Bash command execution working")
            print(f"   Output: {result['stdout'].strip()}")
        else:
            print(f"❌ Bash execution failed: {result['error']}")
            
        # Test directory listing
        result = execute_bash_command("ls -la | head -3")
        if result['success']:
            print("✅ Directory listing working")
            lines = result['stdout'].strip().split('\n')
            print(f"   Found {len(lines)} lines of output")
            
        return True
        
    except Exception as e:
        print(f"❌ Bash tools error: {e}")
        return False


def test_decorators():
    """Test decorator utilities."""
    print("\n🎨 Testing decorators...")
    
    try:
        from tools.decorators import safe_execute, retry
        
        # Test safe execution
        @safe_execute(default_return="fallback value")
        def test_safe_function():
            return "safe execution working"
        
        result = test_safe_function()
        print(f"✅ Safe execute: {result}")
        
        # Test retry mechanism
        call_count = 0
        
        @retry(max_attempts=3, delay=0.1)
        def test_retry_function():
            global call_count
            call_count += 1
            if call_count < 2:
                raise Exception("Intentional test error")
            return "retry working after failure"
        
        result = test_retry_function()
        print(f"✅ Retry mechanism: {result}")
        
        return True
        
    except Exception as e:
        print(f"❌ Decorators error: {e}")
        return False


def demonstrate_framework_concept():
    """Demonstrate the LangManus framework concept."""
    print("\n🏗️ LangManus Framework Concept Demo")
    print("="*50)
    
    print("""
🎯 Core Principle: Generic Framework + Dynamic Tool Injection

Traditional AI Framework (Wrong):
   ┌─────────────────────┐
   │  Business-Specific  │  ← Hard-coded for one domain
   │      Prompts        │
   └─────────────────────┘

LangManus Framework (Right):
   ┌─────────────────────┐
   │   Generic Prompts   │  ← Reusable across domains
   └──────────┬──────────┘
              │
   ┌──────────▼──────────┐
   │   Tool Injection    │  ← Business logic in tools
   └─────────────────────┘

✅ Benefits:
  • Prompts remain generic and reusable
  • Business logic contained in tools
  • Easy to add new domains
  • Framework stays clean and maintainable
""")


def cleanup_test_files():
    """Clean up test files."""
    try:
        import shutil
        if os.path.exists("test_output"):
            shutil.rmtree("test_output")
            print("🧹 Test files cleaned up")
    except Exception as e:
        print(f"⚠️ Cleanup warning: {e}")


def main():
    """Run the complete test suite."""
    print("🚀 LangManus Quick Test Suite")
    print("="*50)
    
    # Ensure output directories exist
    os.makedirs("output", exist_ok=True)
    os.makedirs("test_output", exist_ok=True)
    
    # Run tests
    tests = [
        test_core_imports,
        test_python_tools, 
        test_file_tools,
        test_bash_tools,
        test_decorators
    ]
    
    passed = 0
    total = len(tests)
    
    for test in tests:
        if test():
            passed += 1
    
    # Show framework concept
    demonstrate_framework_concept()
    
    # Results
    print(f"\n📊 Test Results: {passed}/{total} tests passed")
    
    if passed == total:
        print("🎉 All core functionality tests passed!")
        print("✅ LangManus framework is working correctly")
        print("\n💡 Next steps:")
        print("   1. Add your API keys to .env file")
        print("   2. Install missing dependencies: pip install beautifulsoup4 requests")
        print("   3. Run full demo: python3 demo.py")
    else:
        print("⚠️ Some tests failed. Please check the errors above.")
    
    # Cleanup
    cleanup_test_files()


if __name__ == "__main__":
    main() 